### ISSUE TITLE
System.NotSupportedException: 

### ISSUE THREAD

**Issue by Murugamaha** [chuongmep/CadAddinManager#14]
**Describe the bug**
System.NotSupportedException: 'The given path's format is not supported.' in the line,      var directoryInfo = new DirectoryInfo(directory); where directory is /MSBUILD:Installer

**To Reproduce**
1. Download the project
2. Open the Solution
3. Run the installer

**Expected behavior**
Software should get installed

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 OS
 - Visual Studio 2022

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chuongmep** [comment]
Hi @Murugamaha, please follow with step in https://github.com/chuongmep/CadAddinManager/blob/dev/CONTRIBUTING.md to see how to build msi with developer mode, run with exe after build not is right way to create msi test. 
Regard !
