### ISSUE TITLE
Does not seem to have support for LISP Functions

### ISSUE THREAD

**Issue by RedTransit** [chuongmep/CadAddinManager#3]
**Is your feature request related to a problem? Please describe.**
Not a problem, just something that would be a nice addition.

AutoCAD .NET API allows for exposing functions to LISP. Perhaps it would be nice to be able to test these the same way as we do CommandMethods. Perhaps they load up on another tab? Because we would have to pass in result buffers to a LISP call, we would need some way to handle that as well.

More on LISP functions at this link
http://docs.autodesk.com/ACD/2011/ENU/filesMDG/WS1a9193826455f5ff-e569a0121d1945c08-17c3.htm

**Describe the solution you'd like**
A request that I think would make this tool even better. There are of course other ways to test these.

**Describe alternatives you've considered**
Could make CommandMethods to test sub functions called in the LISP Function

**Comment by chuongmep** [comment]
@RedTransit you have any full source example have lisp for this ?
