### ISSUE TITLE
.NET Inserting Block with Embedded Resource File

### ISSUE THREAD

**Issue by RedTransit** [chuongmep/CadAddinManager#4]
**Describe the bug**
Using the .NET API we can insert a block into AutoCAD. For ease of project, it's nice to embed your block DWG file into your project as a resource. Using the code below, we can write this block to a Temp folder out of the resource stream and then insert it as a block file into a file.

Using this code within the CadAddinManager seems to not be able to find the resource. Using the same code when direct loading of the assembly works fine.

Can easily get around this during testing however with just hard coding temporary block path while working out other issues. Just something I noticed that would be nice if there's a fix.

Credit to Norman Yuang for this code on AutoCAD Customization Forum:
https://forums.autodesk.com/t5/net/can-vs-insert-a-dwg-file-as-a-vs-resource/td-p/8422634

```cs        
public static string ExtractFileFromResource(string resourceName)
        {
            dynamic preferences = Application.Preferences;
            string filePathName =
                (string)preferences.Files.TempFilePath + @"\\" + resourceName + @".dwg";

            try
            {
                var bytes = (byte[])accGasWellDesigner.Properties.Resources.ResourceManager.GetObject(resourceName);
                if (File.Exists(filePathName)) File.Delete(filePathName);
                using (var stream = new FileStream(filePathName, FileMode.Create, FileAccess.Write))
                {
                    stream.Write(bytes, 0, bytes.Length);
                    stream.Close();
                }

                return filePathName;
            }
            catch(Exception e)
            {
                //return @"";

                return e.Message.ToString() + ": " + e.StackTrace.ToString();
            }
        }
```

**To Reproduce**
1. Create a test project with an Embedded DWG file as a resource.
2. Use the code above to write the file to a Temp folder
3. Insert the block from the temp folder with the code above
4. See that the block is not found.

**Expected behavior**
Would be nice if we can get this to find the block file.

**Screenshots**
'Block file not found, cannot proceed...' is coming from my code project using the above code for extracting. You can also see in screenshot 'Object reference not set to an instance of object.'
![image](https://user-images.githubusercontent.com/83195049/165801200-a196c757-c02d-4500-88e7-ee0dc5db923d.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Civil 3D 2022

**Comment by chuongmep** [comment]
Hi @RedTransit, 
Many thanks about this ideal, you have any full source about this in github ?

**Comment by RedTransit** [comment]
Sorry, no I don't have one that I can share at the moment. I'll try to put something together this week.

**Comment by chuongmep** [comment]
Tested, it is working now, you can try with latest version and sample: https://github.com/chuongmep/CadAddinManager/blob/dev/Test/ExtractFileFromResources.cs
