### ISSUE TITLE
Unable to use Fabrication API in CADmep

### ISSUE THREAD

**Issue by onomou** [chuongmep/CadAddinManager#6]
I am trying to use Addin Manager with the CADmep API. I receive an error `Exception has been thrown by the target of an invocation.` when running any methods that use the Fabrication API dll.

Running in the debugger, I found that the error comes from [AddinManagerBase.cs, line 103](https://github.com/chuongmep/CadAddinManager/blob/c4df978d4db7e6c4163298e9abfacf86dccbf662/CadAddinManager/Command/AddinManagerBase.cs#L103). `Activator.CreateInstance()` throws an exception `System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'`

There are two inner exceptions.

![2022-06-10 14 40 36 devenv_Ia0ZIWeZ0H](https://user-images.githubusercontent.com/131693/173157179-72b68ab2-e31b-4242-93e6-2d52fcc79e82.png)

```
FileLoadException: Could not load file or assembly 'FabricationAPI, Version=2020.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
```

and

```
ArgumentException: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at CadAddinManager.Model.AssemLoader.SearchAssemblyFileInTempFolder(String assemName)
```

I noticed that `FabricationAPI.dll` is not copied to the running location.

![2022-06-10 14 42 51 explorer_QJIwKsVR5U](https://user-images.githubusercontent.com/131693/173155571-840d10df-d01c-4557-b095-0c7ba76c858e.png)

I wonder if this has anything to do with Addin Manager not checking for FabricationAPI.dll or accore.dll in [the assembly loader](https://github.com/chuongmep/CadAddinManager/blob/4f2ae586407170599da88ce3cea013d2756c155a/CadAddinManager/Model/AssemLoader.cs#L417). 

**Desktop**
 - OS: Windows 10
 - CadAddinManager version: 1.0.7 release
 - AutoCAD version: 2020
 - CADmep version: 2020

**To Reproduce**
1. Create new Class Library
2. Add references to acmdg.dll, accoremgd.dll, acdbmgd.dll (AutoCAD folder), and FabricationAPI.dll
3. Paste in the example C# code
4. Run `Class1.Execute` from Addin Manager
5. Get error `Exception has been thrown by the target of an invocation.`
6. ~~Profit~~

```c#
using Autodesk.AutoCAD.Runtime;

namespace FabricationAddin
{
    public class FabricationInteractions
    {
        [CommandMethod("DoFabricationThing")]
        public void Execute()
        {
            var m = Autodesk.Fabrication.DB.Database.Materials;
        }
    }
}
```

**Comment by chuongmep** [comment]
Thanks @onomou reported, at the moment when i do with this product, i only think to core product autocad and civil, CADmep is not include in my target , so i think this is not a bug, i will think about improvement product to support CADmep.

**Comment by onomou** [comment]
I see what you are saying, not really a bug. What about adding the ability to copy additional DLL files with the specified one? In the Revit Addin Manager, it gives the option to copy the whole folder. I think the AutoCAD Addin Manager loading code is nearly the same, but I never get the option to copy the whole folder, even if it is over the limit (I think [50MB](https://github.com/chuongmep/CadAddinManager/blob/58dadd95560f352e3397f9f7681ab744a7fba9f4/CadAddinManager/Model/FileUtils.cs#L129)). The program appears to only copy my DLL without any dependencies to the running folder (screenshot in the original post).

**Comment by chuongmep** [comment]
> 

Correct , because **FabricationAPI.dll** is defaut of cadmep, and it will automatic load assembly this when you open CADmep, we don't need add it like **acdbmgd**, but with CADmep.CADmep working like a submodule of autocad, so need a other way to can execute same with process if you want use visual studio to debug it.
