### ISSUE TITLE
Is can also work.in autocad 2017 or autocad 2019

### ISSUE THREAD

**Issue by daboho** [chuongmep/CadAddinManager#7]
**Is your feature work in autocad 2107

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chuongmep** [comment]
Hi @daboh, it supports for R15-R23, so AutoCAD 2017 to AutoCAD 2019 is support, but I don't sure that it work perfect, I recommend use from 2020 or higher.
![image](https://user-images.githubusercontent.com/31106432/176987226-563df53b-56cd-4b0c-ad3d-458dfd261f00.png)
