### ISSUE TITLE
Loading references

### ISSUE THREAD

**Issue by shtirlitsDva** [chuongmep/CadAddinManager#8]
Hi
Is there a way to load references added to the project which I am debugging?

I mean, if I use nuget packages or reference another project's dll, it won't be available when I use this program -- the command will throw an exception saying that it can't find the referenced dll.

I also had this problem with netreload. I have worked around this problem by linking my source files around instead of referencing projects and instead of using nuget, I had to download source and also link it in the debugged project to be able to use netreload.

There seems to be same problem with this manager also. I don't know enough about .net to solve the problem my self.

**Comment by chuongmep** [comment]
Hi @shtirlitsDva many thank for your report, do you have any project sample to help me create again this problem ?

**Comment by chuongmep** [comment]
This issues can't create again, so I will close it like resolved.
